# Generated by bower2nix v3.2.0 (https://github.com/rvl/bower2nix)
# unpack and cd into uchiwa; bower2nix ./bower.json > uchiwa-web-deps.nix
{ fetchbower, buildEnv }:
buildEnv { name = "bower-env"; ignoreCollisions = true; paths = [
  (fetchbower "uchiwa-web" "0.14.2" "0.14.2" "14ww1ms2yfmpvd3n2c230p0qdkm8n38vk40l5xgwlqv6mbf23q3w")
  (fetchbower "angular" "1.4.14" "~1.4" "08yhkccgbylzkwv0f9hiapzyxl7l4lrw1sak1qcyld7d65985zyf")
  (fetchbower "angular-bootstrap" "0.13.4" "~0.13.0" "102bxj7m1hjkiq9a7i5hm2d48zj7wk9a440kck053df2nnhc0f95")
  (fetchbower "angular-cookies" "1.4.14" "~1.4" "0kx7nsixq06zf8n75s756wyfkr6qvhy8bwpcs0qr60azbry41mr7")
  (fetchbower "angular-gravatar" "0.3.2" "~0.3.1" "0r1r0l5a2kww38qgzxfjq7mjr0ci7ram6w2d90m4sg02d48lvzg3")
  (fetchbower "angular-moment" "0.9.2" "~0.9.0" "1wsci57q5q1rinhh2y0vvipbin6m37r9mpq1ka4r3bnqb55bi7kj")
  (fetchbower "angular-route" "1.4.14" "~1.4" "1dnsfhrzhlq0x215s71smnxdvsfr4wp7sw4jbxljhjskmcvy39n8")
  (fetchbower "angular-sanitize" "1.4.14" "~1.4" "12gimyd585g6ab1f2zha8j5zqjgcqg7i45y4fp3g8aa303jnjljg")
  (fetchbower "angular-toastr" "1.6.0" "1.6.0" "1szigf1m28bgpfyg8hbm5rffr5zi7wr9n73nc1fqhk0yqh7gzysh")
  (fetchbower "bootstrap" "3.1.1" "3.1.1" "1a06mx1rw5h4wq89kqpa8g2pbiddm3p21dxq50jyi29sywd01ny4")
  (fetchbower "bootstrap-sass-official" "3.1.1" "3.1.1" "1k6hhvsd75hdfrz8qcjzmb12c17fdn0h3l3l5k9wgd0rfhhfkyvd")
  (fetchbower "fontawesome" "4.4.0" "~4.4.0" "09mrbik8i3skjwchn7ns2020bqmb51kbd3mqi59vh444s4az2sc7")
  (fetchbower "highlightjs" "8.3.0" "~8.3.0" "1819gcgnca68a5cqil454gbcdd3cq0irpdx8hfvzp7lq0drw3bd7")
  (fetchbower "moment" "2.8.4" "~2.8.3" "1fixrya902q0s7kwy8wclskl9y6jwbhdl32v0qlsv4shh63ilypn")
  (fetchbower "underscore" "1.6.0" "~1.6.0" "1f9kh0q5y5y9gibrv9w1k5ca76xj1alb175c7179rn5yjzjh1c2g")
  (fetchbower "jquery" "3.3.1" ">= 1.9.0" "1l891s3vgnpi1g8ksplid9jvrvnnv6lci8vraix4ssy50i264rkx")
]; }

